### ISSUE TITLE
Possible incompatiblity with freetype 2.10.0

### ISSUE THREAD

**Issue by djhoese** [conda-forge/freetype-py-feedstock#1]
Issue: vispy's tests are now failing with missing symbols from freetype:
https://travis-ci.org/vispy/vispy/jobs/507194615#L3365

Error:

```
  File "/home/travis/build/vispy/vispy/vispy/ext/freetype.py", line 12, in <module>
    from freetype import *  # noqa
  File "/home/travis/anaconda/envs/testenv/lib/python3.7/site-packages/freetype/__init__.py", line 21, in <module>
    from freetype.raw import *
  File "/home/travis/anaconda/envs/testenv/lib/python3.7/site-packages/freetype/raw.py", line 249, in <module>
    FT_Outline_Done_Internal       = _lib.FT_Outline_Done_Internal
  File "/home/travis/anaconda/envs/testenv/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/home/travis/anaconda/envs/testenv/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/travis/anaconda/envs/testenv/lib/./libfreetype.so.6: undefined symbol: FT_Outline_Done_Internal
```

I'm a little worried by the message on https://www.freetype.org/

> Additionally, the API reference has been completely overhauled and modernized, as already announced.

See the linked travis job for more environment information.

CC @rougier

**Comment by djhoese** [comment]
Also should note I put this in this feedstock instead of the main package repository because I wasn't sure it wasn't the conda-forge's freetype package's fault.

**Comment by djhoese** [comment]
FYI vispy tests passed forcing freetype<2.10.0.

**Comment by rougier** [comment]
Thanks for the notification. Can you post the issue in [freetype-py](https://github.com/rougier/freetype-py)?

**Comment by djhoese** [comment]
Done https://github.com/rougier/freetype-py/issues/107

**Comment by djhoese** [comment]
This current release should probably be updated to limit the version of freetype or maybe that isn't worth it if the package gets the new version released.
